In [1]:
## dimensional -- how many points of information do you need to get a specific peice of data
## 1 point of reference will not help find the data
## number of points we need is the number of dimensions 
## panda datafram is two dimensions
## it is a panda objet

In [2]:
import pandas as pd

In [3]:
nba = pd.read_csv("nba.csv")

In [10]:
nba.head(1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0

In [11]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [13]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [14]:
nba.shape

(458, 9)

In [15]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [16]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [17]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [18]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [19]:
nba.get_dtype_counts()

float64    4
object     5
dtype: int64

In [20]:
## new data

In [23]:
rev = pd.read_csv("revenue.csv", index_col = "Date")

In [25]:
s = pd.Series([1, 2, 3])

s.sum()

6

In [30]:
rev.sum(axis = 1) ## with index, it moves across rows to get sum, so we can change it to 1 or  =columns , so it would now be calculating off date

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [31]:
nba = pd.read_csv("nba.csv")
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [33]:
nba.Name ## just need to put name of column to extract it, it extracts it as a series

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object

In [37]:
nba.Number

Output = None  #just stops data from returning below

In [39]:
nba["Name"] # this is better call columns because the above method can't call column names with space, this method is a lot less prone to error

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object

In [42]:
nba["Salary"] # it is case sensitive

0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [45]:
nba["Name"].head() #going to get the column as a series and you can call an attribute in sequence

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [46]:
type(nba["Name"]) # returns object

pandas.core.series.Series

In [47]:
## Next we will look at working with multiple columns

In [48]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [52]:
nba[      ["Name", "Team"]      ] #when we extracting two or more columns we get a NEW datafram as the output not a series

                        Name                    Team
0              Avery Bradley          Boston Celtics
1                Jae Crowder          Boston Celtics
2               John Holland          Boston Celtics
3                R.J. Hunter          Boston Celtics
4              Jonas Jerebko          Boston Celtics
5               Amir Johnson          Boston Celtics
6              Jordan Mickey          Boston Celtics
7               Kelly Olynyk          Boston Celtics
8               Terry Rozier          Boston Celtics
9               Marcus Smart          Boston Celtics
10           Jared Sullinger          Boston Celtics
11             Isaiah Thomas          Boston Celtics
12               Evan Turner          Boston Celtics
13               James Young          Boston Celtics
14              Tyler Zeller          Boston Celtics
15          Bojan Bogdanovic           Brooklyn Nets
16              Markel Brown           Brooklyn Nets
17           Wayne Ellington           Brooklyn Nets
18   Rondae Hollis-Jefferson           Brooklyn Nets
19              Jarrett Jack           Brooklyn Nets
20            Sergey Karasev           Brooklyn Nets
21           Sean Kilpatrick           Brooklyn Nets
22              Shane Larkin           Brooklyn Nets
23               Brook Lopez           Brooklyn Nets
24          Chris McCullough           Brooklyn Nets
25               Willie Reed           Brooklyn Nets
26           Thomas Robinson           Brooklyn Nets
27                Henry Sims           Brooklyn Nets
28              Donald Sloan           Brooklyn Nets
29            Thaddeus Young           Brooklyn Nets
..                       ...                     ...
428          Al-Farouq Aminu  Portland Trail Blazers
429          Pat Connaughton  Portland Trail Blazers
430             Allen Crabbe  Portland Trail Blazers
431                 Ed Davis  Portland Trail Blazers
432         Maurice Harkless  Portland Trail Blazers
433         Gerald Henderson  Portland Trail Blazers
434              Chris Kaman  Portland Trail Blazers
435           Meyers Leonard  Portland Trail Blazers
436           Damian Lillard  Portland Trail Blazers
437            C.J. McCollum  Portland Trail Blazers
438             Luis Montero  Portland Trail Blazers
439            Mason Plumlee  Portland Trail Blazers
440            Brian Roberts  Portland Trail Blazers
441              Noah Vonleh  Portland Trail Blazers
442            Trevor Booker               Utah Jazz
443               Trey Burke               Utah Jazz
444               Alec Burks               Utah Jazz
445               Dante Exum               Utah Jazz
446           Derrick Favors               Utah Jazz
447              Rudy Gobert               Utah Jazz
448           Gordon Hayward               Utah Jazz
449              Rodney Hood               Utah Jazz
450               Joe Ingles               Utah Jazz
451            Chris Johnson               Utah Jazz
452               Trey Lyles               Utah Jazz
453             Shelvin Mack               Utah Jazz
454                Raul Neto               Utah Jazz
455             Tibor Pleiss               Utah Jazz
456              Jeff Withey               Utah Jazz
457                      NaN                     NaN

[458 rows x 2 columns]

In [51]:
nba[      ["Team", "Name"]      ] ## This will return the new dataframe, but column order will change

                       Team                     Name
0            Boston Celtics            Avery Bradley
1            Boston Celtics              Jae Crowder
2            Boston Celtics             John Holland
3            Boston Celtics              R.J. Hunter
4            Boston Celtics            Jonas Jerebko
5            Boston Celtics             Amir Johnson
6            Boston Celtics            Jordan Mickey
7            Boston Celtics             Kelly Olynyk
8            Boston Celtics             Terry Rozier
9            Boston Celtics             Marcus Smart
10           Boston Celtics          Jared Sullinger
11           Boston Celtics            Isaiah Thomas
12           Boston Celtics              Evan Turner
13           Boston Celtics              James Young
14           Boston Celtics             Tyler Zeller
15            Brooklyn Nets         Bojan Bogdanovic
16            Brooklyn Nets             Markel Brown
17            Brooklyn Nets          Wayne Ellington
18            Brooklyn Nets  Rondae Hollis-Jefferson
19            Brooklyn Nets             Jarrett Jack
20            Brooklyn Nets           Sergey Karasev
21            Brooklyn Nets          Sean Kilpatrick
22            Brooklyn Nets             Shane Larkin
23            Brooklyn Nets              Brook Lopez
24            Brooklyn Nets         Chris McCullough
25            Brooklyn Nets              Willie Reed
26            Brooklyn Nets          Thomas Robinson
27            Brooklyn Nets               Henry Sims
28            Brooklyn Nets             Donald Sloan
29            Brooklyn Nets           Thaddeus Young
..                      ...                      ...
428  Portland Trail Blazers          Al-Farouq Aminu
429  Portland Trail Blazers          Pat Connaughton
430  Portland Trail Blazers             Allen Crabbe
431  Portland Trail Blazers                 Ed Davis
432  Portland Trail Blazers         Maurice Harkless
433  Portland Trail Blazers         Gerald Henderson
434  Portland Trail Blazers              Chris Kaman
435  Portland Trail Blazers           Meyers Leonard
436  Portland Trail Blazers           Damian Lillard
437  Portland Trail Blazers            C.J. McCollum
438  Portland Trail Blazers             Luis Montero
439  Portland Trail Blazers            Mason Plumlee
440  Portland Trail Blazers            Brian Roberts
441  Portland Trail Blazers              Noah Vonleh
442               Utah Jazz            Trevor Booker
443               Utah Jazz               Trey Burke
444               Utah Jazz               Alec Burks
445               Utah Jazz               Dante Exum
446               Utah Jazz           Derrick Favors
447               Utah Jazz              Rudy Gobert
448               Utah Jazz           Gordon Hayward
449               Utah Jazz              Rodney Hood
450               Utah Jazz               Joe Ingles
451               Utah Jazz            Chris Johnson
452               Utah Jazz               Trey Lyles
453               Utah Jazz             Shelvin Mack
454               Utah Jazz                Raul Neto
455               Utah Jazz             Tibor Pleiss
456               Utah Jazz              Jeff Withey
457                     NaN                      NaN

[458 rows x 2 columns]

In [57]:
nba[["Number","College"]].head(3)

   Number            College
0     0.0              Texas
1    99.0          Marquette
2    30.0  Boston University

In [58]:
select = ["Salary", "Team", "Name"] # you can create a list in python, but if colums mattch up in will return these columns from the dataset, a little cleaner look
nba[select]

         Salary                    Team                     Name
0     7730337.0          Boston Celtics            Avery Bradley
1     6796117.0          Boston Celtics              Jae Crowder
2           NaN          Boston Celtics             John Holland
3     1148640.0          Boston Celtics              R.J. Hunter
4     5000000.0          Boston Celtics            Jonas Jerebko
5    12000000.0          Boston Celtics             Amir Johnson
6     1170960.0          Boston Celtics            Jordan Mickey
7     2165160.0          Boston Celtics             Kelly Olynyk
8     1824360.0          Boston Celtics             Terry Rozier
9     3431040.0          Boston Celtics             Marcus Smart
10    2569260.0          Boston Celtics          Jared Sullinger
11    6912869.0          Boston Celtics            Isaiah Thomas
12    3425510.0          Boston Celtics              Evan Turner
13    1749840.0          Boston Celtics              James Young
14    2616975.0          Boston Celtics             Tyler Zeller
15    3425510.0           Brooklyn Nets         Bojan Bogdanovic
16     845059.0           Brooklyn Nets             Markel Brown
17    1500000.0           Brooklyn Nets          Wayne Ellington
18    1335480.0           Brooklyn Nets  Rondae Hollis-Jefferson
19    6300000.0           Brooklyn Nets             Jarrett Jack
20    1599840.0           Brooklyn Nets           Sergey Karasev
21     134215.0           Brooklyn Nets          Sean Kilpatrick
22    1500000.0           Brooklyn Nets             Shane Larkin
23   19689000.0           Brooklyn Nets              Brook Lopez
24    1140240.0           Brooklyn Nets         Chris McCullough
25     947276.0           Brooklyn Nets              Willie Reed
26     981348.0           Brooklyn Nets          Thomas Robinson
27     947276.0           Brooklyn Nets               Henry Sims
28     947276.0           Brooklyn Nets             Donald Sloan
29   11235955.0           Brooklyn Nets           Thaddeus Young
..          ...                     ...                      ...
428   8042895.0  Portland Trail Blazers          Al-Farouq Aminu
429    625093.0  Portland Trail Blazers          Pat Connaughton
430    947276.0  Portland Trail Blazers             Allen Crabbe
431   6980802.0  Portland Trail Blazers                 Ed Davis
432   2894059.0  Portland Trail Blazers         Maurice Harkless
433   6000000.0  Portland Trail Blazers         Gerald Henderson
434   5016000.0  Portland Trail Blazers              Chris Kaman
435   3075880.0  Portland Trail Blazers           Meyers Leonard
436   4236287.0  Portland Trail Blazers           Damian Lillard
437   2525160.0  Portland Trail Blazers            C.J. McCollum
438    525093.0  Portland Trail Blazers             Luis Montero
439   1415520.0  Portland Trail Blazers            Mason Plumlee
440   2854940.0  Portland Trail Blazers            Brian Roberts
441   2637720.0  Portland Trail Blazers              Noah Vonleh
442   4775000.0               Utah Jazz            Trevor Booker
443   2658240.0               Utah Jazz               Trey Burke
444   9463484.0               Utah Jazz               Alec Burks
445   3777720.0               Utah Jazz               Dante Exum
446  12000000.0               Utah Jazz           Derrick Favors
447   1175880.0               Utah Jazz              Rudy Gobert
448  15409570.0               Utah Jazz           Gordon Hayward
449   1348440.0               Utah Jazz              Rodney Hood
450   2050000.0               Utah Jazz               Joe Ingles
451    981348.0               Utah Jazz            Chris Johnson
452   2239800.0               Utah Jazz               Trey Lyles
453   2433333.0               Utah Jazz             Shelvin Mack
454    900000.0               Utah Jazz                Raul Neto
455   2900000.0               Utah Jazz             Tibor Pleiss
456    947276.0               Utah Jazz              Jeff Withey
457         NaN                     NaN                      NaN

[458 rows x 3 columns]

In [59]:
nba = pd.read_csv("nba.csv")
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [60]:
nba["Sport"] = "Basketball"  ## this will change everything to Basketbal in this new column  ## creating a new column, be sure to not make a new name as it will duplicate

In [61]:
nba.head(3) ## see sport is on the end

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball

In [63]:
nba["League"] = "National Basketball Association"
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,National Basketball Association
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,National Basketball Association
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,National Basketball Association

In [65]:
nba.insert(3, column = "Sports", value = "Basketball") #perm. modifies dataframe , inputs new column in specific location

In [66]:
nba.head(3)

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,National Basketball Association
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,National Basketball Association
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,National Basketball Association

In [67]:
## Broadcasting Operations

In [68]:
nba["Age"].add(5)

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
5      34.0
6      26.0
7      30.0
8      27.0
9      27.0
10     29.0
11     32.0
12     32.0
13     25.0
14     31.0
15     32.0
16     29.0
17     33.0
18     26.0
19     37.0
20     27.0
21     31.0
22     28.0
23     33.0
24     26.0
25     31.0
26     30.0
27     31.0
28     33.0
29     32.0
       ...
428    30.0
429    28.0
430    29.0
431    32.0
432    28.0
433    33.0
434    39.0
435    29.0
436    30.0
437    29.0
438    28.0
439    31.0
440    35.0
441    25.0
442    33.0
443    28.0
444    29.0
445    25.0
446    29.0
447    28.0
448    31.0
449    28.0
450    33.0
451    31.0
452    25.0
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [70]:
nba["Age"] + 5 ## adding a number to object, the column. It is adding 5 to every value in the series, pandas knows what to do

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
5      34.0
6      26.0
7      30.0
8      27.0
9      27.0
10     29.0
11     32.0
12     32.0
13     25.0
14     31.0
15     32.0
16     29.0
17     33.0
18     26.0
19     37.0
20     27.0
21     31.0
22     28.0
23     33.0
24     26.0
25     31.0
26     30.0
27     31.0
28     33.0
29     32.0
       ...
428    30.0
429    28.0
430    29.0
431    32.0
432    28.0
433    33.0
434    39.0
435    29.0
436    30.0
437    29.0
438    28.0
439    31.0
440    35.0
441    25.0
442    33.0
443    28.0
444    29.0
445    25.0
446    29.0
447    28.0
448    31.0
449    28.0
450    33.0
451    31.0
452    25.0
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [75]:
nba["Salary"] - 500000

0       7230337.0
1       6296117.0
2             NaN
3        648640.0
4       4500000.0
5      11500000.0
6        670960.0
7       1665160.0
8       1324360.0
9       2931040.0
10      2069260.0
11      6412869.0
12      2925510.0
13      1249840.0
14      2116975.0
15      2925510.0
16       345059.0
17      1000000.0
18       835480.0
19      5800000.0
20      1099840.0
21      -365785.0
22      1000000.0
23     19189000.0
24       640240.0
25       447276.0
26       481348.0
27       447276.0
28       447276.0
29     10735955.0
          ...
428     7542895.0
429      125093.0
430      447276.0
431     6480802.0
432     2394059.0
433     5500000.0
434     4516000.0
435     2575880.0
436     3736287.0
437     2025160.0
438       25093.0
439      915520.0
440     2354940.0
441     2137720.0
442     4275000.0
443     2158240.0
444     8963484.0
445     3277720.0
446    11500000.0
447      675880.0
448    14909570.0
449      848440.0
450     1550000.0
451      481348.0
452     1739800.0
453     1933333.0
454      400000.0
455     2400000.0
456      447276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [84]:
nba["Weight in Kilograms"] = nba["Weight"] * 0.54 # adds column that has specifc way to be made

In [85]:
nba.head(3)

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary,Sport,League,Weight in Kilograms
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball,National Basketball Association,97.2
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball,National Basketball Association,126.9
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN,Basketball,National Basketball Association,110.7

In [87]:
nba["Team"].value_counts() #counts number of values

New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Indiana Pacers            15
Portland Trail Blazers    15
Houston Rockets           15
Utah Jazz                 15
Phoenix Suns              15
Charlotte Hornets         15
Miami Heat                15
Denver Nuggets            15
Los Angeles Lakers        15
Washington Wizards        15
San Antonio Spurs         15
Los Angeles Clippers      15
Golden State Warriors     15
Sacramento Kings          15
Philadelphia 76ers        15
Oklahoma City Thunder     15
Dallas Mavericks          15
Boston Celtics            15
Toronto Raptors           15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Brooklyn Nets             15
Atlanta Hawks             15
Orlando Magic             14
Minnesota Timberwolves    14
Name: Team, dtype: int64

In [89]:
nba["Position"].value_counts().head(1)

SG    102
Name: Position, dtype: int64

In [96]:
nba["Salary"].value_counts()

947276.0      31
845059.0      18
525093.0      13
981348.0       6
1100602.0      5
16407500.0     5
5000000.0      5
12000000.0     5
8000000.0      5
4000000.0      5
3000000.0      4
7000000.0      4
2814000.0      4
1000000.0      4
19689000.0     4
200600.0       3
8500000.0      3
2500000.0      3
1015421.0      3
2854940.0      3
13500000.0     3
5543725.0      3
2288205.0      2
1270964.0      2
2900000.0      2
1007026.0      2
111444.0       2
13000000.0     2
1500000.0      2
1842000.0      2
              ..
2239800.0      1
1474440.0      1
19688000.0     1
7900000.0      1
2008748.0      1
13800000.0     1
2841960.0      1
1404600.0      1
1584480.0      1
273038.0       1
9213483.0      1
3272091.0      1
3075880.0      1
2250000.0      1
4626960.0      1
1304520.0      1
12100000.0     1
7500000.0      1
295327.0       1
2836186.0      1
6486486.0      1
5016000.0      1
3333333.0      1
1824360.0      1
8042895.0      1
1242720.0      1
2489530.0      1
5103120.0      1
9463484.0      1
700902.0       1
Name: Salary, Length: 309, dtype: int64

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [4]:
nba.dropna()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [6]:
nba.dropna(how= "all") ## removes rows were all are null

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [7]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
nba.dropna(how = "all").tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [11]:
nba.dropna(axis= "columns").tail() ## remove any columns that have null valeus

Empty DataFrame
Columns: []
Index: [453, 454, 455, 456, 457]

In [12]:
nba.dropna(subset = ["Salary"])## will only drop the rows that are NA in the specified column

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

Fill in null values with fillna()

In [15]:
nba.fillna(0) ## all nan's turnt to 0 (note will not adjust datatypes)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,0,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,0,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,0,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,0,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,0,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,0,0,0.0,0,0.0,0,0.0,0,0.0

In [20]:
nba["Salary"].fillna(0, inplace = True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [21]:
nba["College"].fillna("No College", inplace = True)

astype() method, you cant use it unless there are NO NaN values

In [24]:
nba.dropna(how = "all")
nba["Salary"].fillna(0, inplace = True)
nba["College"].fillna("No College", inplace = True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000.0

In [25]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [26]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     458 non-null object
Salary      458 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [32]:
nba["Salary"] = nba["Salary"].astype("int") # change column data type

In [34]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000

In [40]:
nba["Number"].fillna(0, inplace = True)

nba["Number"] = nba["Number"].astype("int")

Category is a dataype only in pandas , it is used for a small type of data / unique values against a large dataset

In [43]:
nba["Position"].nunique() # we have five unique values in position column, so ideal to turn this into a Category, we will have 5 objets apposed to 450000 strings

5

In [44]:
nba["Position"] = nba["Position"].astype("category")

In [46]:
nba.info() #note that the memory is less

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      458 non-null int32
Position    457 non-null category
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     458 non-null object
Salary      458 non-null int32
dtypes: category(1), float64(2), int32(2), object(4)
memory usage: 25.8+ KB

In [47]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000

In [51]:
nba.sort_values("Name", ascending = "false").head() #default is it will sort the data by the column specified and ascending order

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0,PG,31.0,6-0,161.0,Oregon,2250000
356,Aaron Gordon,Orlando Magic,0,PF,20.0,6-9,220.0,Arizona,4171680
328,Aaron Harrison,Charlotte Hornets,9,SG,21.0,6-6,210.0,Kentucky,525093
404,Adreian Payne,Minnesota Timberwolves,33,PF,25.0,6-10,237.0,Michigan State,1938840
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000

In [52]:
nba.sort_values("Salary",na_position = "first") # puts NA's on top or you could make them on bottom

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
397,Axel Toupane,Denver Nuggets,6,SG,23.0,6-7,210.0,No College,0
171,Dahntay Jones,Cleveland Cavaliers,30,SG,35.0,6-6,225.0,Duke,0
409,Greg Smith,Minnesota Timberwolves,4,PF,25.0,6-10,250.0,Fresno State,0
353,Dorell Wright,Miami Heat,11,SF,30.0,6-9,205.0,No College,0
350,Briante Weber,Miami Heat,12,PG,23.0,6-2,165.0,Virginia Commonwealth,0
46,Elton Brand,Philadelphia 76ers,42,PF,37.0,6-9,254.0,Duke,0
264,Jordan Farmar,Memphis Grizzlies,4,PG,29.0,6-2,180.0,UCLA,0
269,Ray McCallum,Memphis Grizzlies,5,PG,24.0,6-3,190.0,Detroit,0
270,Xavier Munford,Memphis Grizzlies,14,PG,24.0,6-3,180.0,Rhode Island,0
273,Alex Stepheson,Memphis Grizzlies,35,PF,28.0,6-10,270.0,USC,0
32,Thanasis Antetokounmpo,New York Knicks,43,SF,23.0,6-7,205.0,No College,30888
130,Phil Pressey,Phoenix Suns,25,PG,25.0,5-11,175.0,Missouri,55722
291,Orlando Johnson,New Orleans Pelicans,0,SG,27.0,6-5,220.0,UC Santa Barbara,55722
135,Alan Williams,Phoenix Suns,15,C,23.0,6-8,260.0,UC Santa Barbara,83397
175,Jordan McRae,Cleveland Cavaliers,12,SG,25.0,6-5,179.0,Tennessee,111196
92,Jeff Ayres,Los Angeles Clippers,19,PF,29.0,6-9,250.0,Arizona State,111444
184,Lorenzo Brown,Detroit Pistons,17,PG,25.0,6-5,189.0,North Carolina State,111444
21,Sean Kilpatrick,Brooklyn Nets,6,SG,26.0,6-4,219.0,Cincinnati,134215
45,Tony Wroten,New York Knicks,5,SG,23.0,6-6,205.0,Washington,167406
282,Bryce Dejean-Jones,New Orleans Pelicans,31,SG,23.0,6-6,203.0,Iowa State,169883
326,Jorge Gutierrez,Charlotte Hornets,12,PG,27.0,6-3,189.0,California,189455
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
248,Andrew Goudelock,Houston Rockets,0,PG,27.0,6-3,200.0,Charleston,200600
303,Kevin Martin,San Antonio Spurs,23,SG,33.0,6-7,199.0,Western Carolina,200600
123,Chase Budinger,Phoenix Suns,10,SF,28.0,6-7,209.0,Arizona,206192
203,Ty Lawson,Indiana Pacers,10,PG,28.0,5-11,195.0,North Carolina,211744
420,Nazr Mohammed,Oklahoma City Thunder,13,C,38.0,6-10,250.0,Kentucky,222888
73,Jason Thompson,Toronto Raptors,1,PF,29.0,6-11,250.0,Rider,245177
...,...,...,...,...,...,...,...,...,...
288,Eric Gordon,New Orleans Pelicans,10,SG,27.0,6-4,215.0,Indiana,15514031
111,Roy Hibbert,Los Angeles Lakers,17,C,29.0,7-2,270.0,Georgetown,15592217
249,James Harden,Houston Rockets,13,SG,26.0,6-5,220.0,Arizona State,15756438
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
143,DeMarcus Cousins,Sacramento Kings,15,C,25.0,6-11,270.0,Kentucky,15851950
189,Tobias Harris,Detroit Pistons,34,SF,23.0,6-9,235.0,Tennessee,16000000
418,Enes Kanter,Oklahoma City Thunder,11,C,24.0,6-11,245.0,Kentucky,16407500
220,Greg Monroe,Milwaukee Bucks,15,C,26.0,6-11,265.0,Georgetown,16407500
301,Kawhi Leonard,San Antonio Spurs,2,SF,24.0,6-7,230.0,San Diego State,16407500
233,Wesley Matthews,Dallas Mavericks,23,SG,29.0,6-5,220.0,Marquette,16407500
153,Jimmy Butler,Chicago Bulls,21,SG,26.0,6-7,220.0,Marquette,16407500
168,Kyrie Irving,Cleveland Cavaliers,2,PG,24.0,6-3,193.0,Duke,16407501
426,Russell Westbrook,Oklahoma City Thunder,0,PG,27.0,6-3,200.0,UCLA,16744218
199,Paul George,Indiana Pacers,13,SF,26.0,6-9,220.0,Fresno State,17120106
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
96,Blake Griffin,Los Angeles Clippers,32,PF,27.0,6-10,251.0,Oklahoma,18907726
265,Marc Gasol,Memphis Grizzlies,33,C,31.0,7-1,255.0,No College,19688000
23,Brook Lopez,Brooklyn Nets,11,C,28.0,7-0,275.0,Stanford,19689000
294,LaMarcus Aldridge,San Antonio Spurs,12,PF,30.0,6-11,240.0,Texas,19689000
98,DeAndre Jordan,Los Angeles Clippers,6,C,27.0,6-11,265.0,Texas A&M,19689000
174,Kevin Love,Cleveland Cavaliers,0,PF,27.0,6-10,251.0,UCLA,19689000
349,Dwyane Wade,Miami Heat,3,SG,34.0,6-4,220.0,Marquette,20000000
164,Derrick Rose,Chicago Bulls,1,PG,27.0,6-3,190.0,Memphis,20093064
414,Kevin Durant,Oklahoma City Thunder,35,SF,27.0,6-9,240.0,Texas,20158622
100,Chris Paul,Los Angeles Clippers,3,PG,31.0,6-0,175.0,Wake Forest,21468695
339,Chris Bosh,Miami Heat,1,PF,32.0,6-11,235.0,Georgia Tech,22192730
251,Dwight Howard,Houston Rockets,12,C,30.0,6-11,265.0,No College,22359364
33,Carmelo Anthony,New York Knicks,7,SF,32.0,6-8,240.0,Syracuse,22875000
169,LeBron James,Cleveland Cavaliers,23,SF,31.0,6-8,250.0,No College,22970500
109,Kobe Bryant,Los Angeles Lakers,24,SF,37.0,6-6,212.0,No College,25000000

In [54]:
nba.sort_values("Salary", ascending = False, na_position = "first") # puts NA's on top or you could make them on bottom and you can then still have the ascending features work

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24,SF,37.0,6-6,212.0,No College,25000000
169,LeBron James,Cleveland Cavaliers,23,SF,31.0,6-8,250.0,No College,22970500
33,Carmelo Anthony,New York Knicks,7,SF,32.0,6-8,240.0,Syracuse,22875000
251,Dwight Howard,Houston Rockets,12,C,30.0,6-11,265.0,No College,22359364
339,Chris Bosh,Miami Heat,1,PF,32.0,6-11,235.0,Georgia Tech,22192730
100,Chris Paul,Los Angeles Clippers,3,PG,31.0,6-0,175.0,Wake Forest,21468695
414,Kevin Durant,Oklahoma City Thunder,35,SF,27.0,6-9,240.0,Texas,20158622
164,Derrick Rose,Chicago Bulls,1,PG,27.0,6-3,190.0,Memphis,20093064
349,Dwyane Wade,Miami Heat,3,SG,34.0,6-4,220.0,Marquette,20000000
23,Brook Lopez,Brooklyn Nets,11,C,28.0,7-0,275.0,Stanford,19689000
98,DeAndre Jordan,Los Angeles Clippers,6,C,27.0,6-11,265.0,Texas A&M,19689000
174,Kevin Love,Cleveland Cavaliers,0,PF,27.0,6-10,251.0,UCLA,19689000
294,LaMarcus Aldridge,San Antonio Spurs,12,PF,30.0,6-11,240.0,Texas,19689000
265,Marc Gasol,Memphis Grizzlies,33,C,31.0,7-1,255.0,No College,19688000
96,Blake Griffin,Los Angeles Clippers,32,PF,27.0,6-10,251.0,Oklahoma,18907726
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
199,Paul George,Indiana Pacers,13,SF,26.0,6-9,220.0,Fresno State,17120106
426,Russell Westbrook,Oklahoma City Thunder,0,PG,27.0,6-3,200.0,UCLA,16744218
168,Kyrie Irving,Cleveland Cavaliers,2,PG,24.0,6-3,193.0,Duke,16407501
418,Enes Kanter,Oklahoma City Thunder,11,C,24.0,6-11,245.0,Kentucky,16407500
220,Greg Monroe,Milwaukee Bucks,15,C,26.0,6-11,265.0,Georgetown,16407500
301,Kawhi Leonard,San Antonio Spurs,2,SF,24.0,6-7,230.0,San Diego State,16407500
153,Jimmy Butler,Chicago Bulls,21,SG,26.0,6-7,220.0,Marquette,16407500
233,Wesley Matthews,Dallas Mavericks,23,SG,29.0,6-5,220.0,Marquette,16407500
189,Tobias Harris,Detroit Pistons,34,SF,23.0,6-9,235.0,Tennessee,16000000
143,DeMarcus Cousins,Sacramento Kings,15,C,25.0,6-11,270.0,Kentucky,15851950
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
249,James Harden,Houston Rockets,13,SG,26.0,6-5,220.0,Arizona State,15756438
111,Roy Hibbert,Los Angeles Lakers,17,C,29.0,7-2,270.0,Georgetown,15592217
288,Eric Gordon,New Orleans Pelicans,10,SG,27.0,6-4,215.0,Indiana,15514031
...,...,...,...,...,...,...,...,...,...
73,Jason Thompson,Toronto Raptors,1,PF,29.0,6-11,250.0,Rider,245177
420,Nazr Mohammed,Oklahoma City Thunder,13,C,38.0,6-10,250.0,Kentucky,222888
203,Ty Lawson,Indiana Pacers,10,PG,28.0,5-11,195.0,North Carolina,211744
123,Chase Budinger,Phoenix Suns,10,SF,28.0,6-7,209.0,Arizona,206192
303,Kevin Martin,San Antonio Spurs,23,SG,33.0,6-7,199.0,Western Carolina,200600
248,Andrew Goudelock,Houston Rockets,0,PG,27.0,6-3,200.0,Charleston,200600
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
326,Jorge Gutierrez,Charlotte Hornets,12,PG,27.0,6-3,189.0,California,189455
282,Bryce Dejean-Jones,New Orleans Pelicans,31,SG,23.0,6-6,203.0,Iowa State,169883
45,Tony Wroten,New York Knicks,5,SG,23.0,6-6,205.0,Washington,167406
21,Sean Kilpatrick,Brooklyn Nets,6,SG,26.0,6-4,219.0,Cincinnati,134215
184,Lorenzo Brown,Detroit Pistons,17,PG,25.0,6-5,189.0,North Carolina State,111444
92,Jeff Ayres,Los Angeles Clippers,19,PF,29.0,6-9,250.0,Arizona State,111444
175,Jordan McRae,Cleveland Cavaliers,12,SG,25.0,6-5,179.0,Tennessee,111196
135,Alan Williams,Phoenix Suns,15,C,23.0,6-8,260.0,UC Santa Barbara,83397
130,Phil Pressey,Phoenix Suns,25,PG,25.0,5-11,175.0,Missouri,55722
291,Orlando Johnson,New Orleans Pelicans,0,SG,27.0,6-5,220.0,UC Santa Barbara,55722
32,Thanasis Antetokounmpo,New York Knicks,43,SF,23.0,6-7,205.0,No College,30888
350,Briante Weber,Miami Heat,12,PG,23.0,6-2,165.0,Virginia Commonwealth,0
171,Dahntay Jones,Cleveland Cavaliers,30,SG,35.0,6-6,225.0,Duke,0
353,Dorell Wright,Miami Heat,11,SF,30.0,6-9,205.0,No College,0
46,Elton Brand,Philadelphia 76ers,42,PF,37.0,6-9,254.0,Duke,0
397,Axel Toupane,Denver Nuggets,6,SG,23.0,6-7,210.0,No College,0
273,Alex Stepheson,Memphis Grizzlies,35,PF,28.0,6-10,270.0,USC,0
270,Xavier Munford,Memphis Grizzlies,14,PG,24.0,6-3,180.0,Rhode Island,0
269,Ray McCallum,Memphis Grizzlies,5,PG,24.0,6-3,190.0,Detroit,0
409,Greg Smith,Minnesota Timberwolves,4,PF,25.0,6-10,250.0,Fresno State,0
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
264,Jordan Farmar,Memphis Grizzlies,4,PG,29.0,6-2,180.0,UCLA,0
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0

In [56]:
nba.sort_values(["Team", "Name"]) # sorts the team then the name alphabetically

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000
318,Dennis Schroder,Atlanta Hawks,17,PG,22.0,6-1,172.0,No College,1763400
323,Jeff Teague,Atlanta Hawks,0,PG,27.0,6-2,186.0,Wake Forest,8000000
309,Kent Bazemore,Atlanta Hawks,24,SF,26.0,6-5,201.0,Old Dominion,2000000
311,Kirk Hinrich,Atlanta Hawks,12,SG,35.0,6-4,190.0,Kansas,2854940
313,Kris Humphries,Atlanta Hawks,43,PF,31.0,6-9,235.0,Minnesota,1000000
314,Kyle Korver,Atlanta Hawks,26,SG,35.0,6-7,212.0,Creighton,5746479
317,Lamar Patterson,Atlanta Hawks,13,SG,24.0,6-5,225.0,Pittsburgh,525093
316,Mike Muscala,Atlanta Hawks,31,PF,24.0,6-11,240.0,Bucknell,947276
319,Mike Scott,Atlanta Hawks,32,PF,27.0,6-8,237.0,Virginia,3333333
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
320,Thabo Sefolosha,Atlanta Hawks,25,SF,32.0,6-7,220.0,No College,4000000
321,Tiago Splitter,Atlanta Hawks,11,C,31.0,6-11,245.0,No College,9756250
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24.0,6-6,205.0,Michigan,1304520
322,Walter Tavares,Atlanta Hawks,22,C,24.0,7-3,260.0,No College,1000000
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,No College,12000000
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
...,...,...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,No College,3777720
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,No College,2050000
454,Raul Neto,Utah Jazz,25,PG,24.0,6-1,179.0,No College,900000
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,No College,1175880
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,No College,2900000
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
452,Trey Lyles,Utah Jazz,41,PF,20.0,6-10,234.0,Kentucky,2239800
368,Alan Anderson,Washington Wizards,6,SG,33.0,6-6,220.0,Michigan State,4000000
369,Bradley Beal,Washington Wizards,3,SG,22.0,6-5,207.0,Florida,5694674
372,Drew Gooden,Washington Wizards,90,PF,34.0,6-10,250.0,Kansas,3300000
380,Garrett Temple,Washington Wizards,17,SG,30.0,6-6,195.0,LSU,1100602
374,JJ Hickson,Washington Wizards,21,C,27.0,6-9,242.0,North Carolina State,273038
370,Jared Dudley,Washington Wizards,1,SF,30.0,6-7,225.0,Boston College,4375000
371,Jarell Eddie,Washington Wizards,8,SG,24.0,6-7,218.0,Virginia Tech,561716
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
377,Kelly Oubre Jr.,Washington Wizards,12,SF,20.0,6-7,205.0,Kansas,1920240
373,Marcin Gortat,Washington Wizards,13,C,32.0,6-11,240.0,No College,11217391
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
376,Markieff Morris,Washington Wizards,5,PF,26.0,6-10,245.0,Kansas,8000000
375,Nene Hilario,Washington Wizards,42,C,33.0,6-11,250.0,No College,13000000
378,Otto Porter Jr.,Washington Wizards,22,SF,23.0,6-8,198.0,Georgetown,4662960
379,Ramon Sessions,Washington Wizards,7,PG,30.0,6-3,190.0,Nevada,2170465
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0

In [58]:
nba.sort_values(["Team", "Name"], ascending = [True, False]) ## makes team ascending and name descending

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,22,C,24.0,7-3,260.0,No College,1000000
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24.0,6-6,205.0,Michigan,1304520
321,Tiago Splitter,Atlanta Hawks,11,C,31.0,6-11,245.0,No College,9756250
320,Thabo Sefolosha,Atlanta Hawks,25,SF,32.0,6-7,220.0,No College,4000000
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
319,Mike Scott,Atlanta Hawks,32,PF,27.0,6-8,237.0,Virginia,3333333
316,Mike Muscala,Atlanta Hawks,31,PF,24.0,6-11,240.0,Bucknell,947276
317,Lamar Patterson,Atlanta Hawks,13,SG,24.0,6-5,225.0,Pittsburgh,525093
314,Kyle Korver,Atlanta Hawks,26,SG,35.0,6-7,212.0,Creighton,5746479
313,Kris Humphries,Atlanta Hawks,43,PF,31.0,6-9,235.0,Minnesota,1000000
311,Kirk Hinrich,Atlanta Hawks,12,SG,35.0,6-4,190.0,Kansas,2854940
309,Kent Bazemore,Atlanta Hawks,24,SF,26.0,6-5,201.0,Old Dominion,2000000
323,Jeff Teague,Atlanta Hawks,0,PG,27.0,6-2,186.0,Wake Forest,8000000
318,Dennis Schroder,Atlanta Hawks,17,PG,22.0,6-1,172.0,No College,1763400
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,No College,12000000
...,...,...,...,...,...,...,...,...,...
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,No College,2900000
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,No College,1175880
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
454,Raul Neto,Utah Jazz,25,PG,24.0,6-1,179.0,No College,900000
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,No College,2050000
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,No College,3777720
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
444,Alec Burks,Utah Jazz,10,SG,24.0,6-6,214.0,Colorado,9463484
379,Ramon Sessions,Washington Wizards,7,PG,30.0,6-3,190.0,Nevada,2170465
378,Otto Porter Jr.,Washington Wizards,22,SF,23.0,6-8,198.0,Georgetown,4662960
375,Nene Hilario,Washington Wizards,42,C,33.0,6-11,250.0,No College,13000000
376,Markieff Morris,Washington Wizards,5,PF,26.0,6-10,245.0,Kansas,8000000
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
373,Marcin Gortat,Washington Wizards,13,C,32.0,6-11,240.0,No College,11217391
377,Kelly Oubre Jr.,Washington Wizards,12,SF,20.0,6-7,205.0,Kansas,1920240
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
371,Jarell Eddie,Washington Wizards,8,SG,24.0,6-7,218.0,Virginia Tech,561716
370,Jared Dudley,Washington Wizards,1,SF,30.0,6-7,225.0,Boston College,4375000
374,JJ Hickson,Washington Wizards,21,C,27.0,6-9,242.0,North Carolina State,273038
380,Garrett Temple,Washington Wizards,17,SG,30.0,6-6,195.0,LSU,1100602
372,Drew Gooden,Washington Wizards,90,PF,34.0,6-10,250.0,Kansas,3300000
369,Bradley Beal,Washington Wizards,3,SG,22.0,6-5,207.0,Florida,5694674
368,Alan Anderson,Washington Wizards,6,SG,33.0,6-6,220.0,Michigan State,4000000
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0

In [60]:
nba.sort_values(["Team", "Salary","Name"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
317,Lamar Patterson,Atlanta Hawks,13,SG,24.0,6-5,225.0,Pittsburgh,525093
316,Mike Muscala,Atlanta Hawks,31,PF,24.0,6-11,240.0,Bucknell,947276
313,Kris Humphries,Atlanta Hawks,43,PF,31.0,6-9,235.0,Minnesota,1000000
322,Walter Tavares,Atlanta Hawks,22,C,24.0,7-3,260.0,No College,1000000
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24.0,6-6,205.0,Michigan,1304520
318,Dennis Schroder,Atlanta Hawks,17,PG,22.0,6-1,172.0,No College,1763400
309,Kent Bazemore,Atlanta Hawks,24,SF,26.0,6-5,201.0,Old Dominion,2000000
311,Kirk Hinrich,Atlanta Hawks,12,SG,35.0,6-4,190.0,Kansas,2854940
319,Mike Scott,Atlanta Hawks,32,PF,27.0,6-8,237.0,Virginia,3333333
320,Thabo Sefolosha,Atlanta Hawks,25,SF,32.0,6-7,220.0,No College,4000000
314,Kyle Korver,Atlanta Hawks,26,SG,35.0,6-7,212.0,Creighton,5746479
323,Jeff Teague,Atlanta Hawks,0,PG,27.0,6-2,186.0,Wake Forest,8000000
321,Tiago Splitter,Atlanta Hawks,11,C,31.0,6-11,245.0,No College,9756250
312,Al Horford,Atlanta Hawks,15,C,30.0,6-10,245.0,Florida,12000000
315,Paul Millsap,Atlanta Hawks,4,PF,31.0,6-8,246.0,Louisiana Tech,18671659
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,No College,12000000
...,...,...,...,...,...,...,...,...,...
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,No College,1175880
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,No College,2050000
452,Trey Lyles,Utah Jazz,41,PF,20.0,6-10,234.0,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,No College,2900000
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,No College,3777720
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
444,Alec Burks,Utah Jazz,10,SG,24.0,6-6,214.0,Colorado,9463484
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
381,Marcus Thornton,Washington Wizards,15,SF,29.0,6-4,205.0,LSU,200600
374,JJ Hickson,Washington Wizards,21,C,27.0,6-9,242.0,North Carolina State,273038
371,Jarell Eddie,Washington Wizards,8,SG,24.0,6-7,218.0,Virginia Tech,561716
380,Garrett Temple,Washington Wizards,17,SG,30.0,6-6,195.0,LSU,1100602
377,Kelly Oubre Jr.,Washington Wizards,12,SF,20.0,6-7,205.0,Kansas,1920240
379,Ramon Sessions,Washington Wizards,7,PG,30.0,6-3,190.0,Nevada,2170465
372,Drew Gooden,Washington Wizards,90,PF,34.0,6-10,250.0,Kansas,3300000
368,Alan Anderson,Washington Wizards,6,SG,33.0,6-6,220.0,Michigan State,4000000
370,Jared Dudley,Washington Wizards,1,SF,30.0,6-7,225.0,Boston College,4375000
378,Otto Porter Jr.,Washington Wizards,22,SF,23.0,6-8,198.0,Georgetown,4662960
369,Bradley Beal,Washington Wizards,3,SG,22.0,6-5,207.0,Florida,5694674
376,Markieff Morris,Washington Wizards,5,PF,26.0,6-10,245.0,Kansas,8000000
373,Marcin Gortat,Washington Wizards,13,C,32.0,6-11,240.0,No College,11217391
375,Nene Hilario,Washington Wizards,42,C,33.0,6-11,250.0,No College,13000000
382,John Wall,Washington Wizards,2,PG,25.0,6-4,195.0,Kentucky,15851950
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0

In [64]:
nba.sort_index()
# in place makes it true

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000
5,Amir Johnson,Boston Celtics,90,PF,29.0,6-9,240.0,No College,12000000
6,Jordan Mickey,Boston Celtics,55,PF,21.0,6-8,235.0,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41,C,25.0,7-0,238.0,Gonzaga,2165160
8,Terry Rozier,Boston Celtics,12,PG,22.0,6-2,190.0,Louisville,1824360
9,Marcus Smart,Boston Celtics,36,PG,22.0,6-4,220.0,Oklahoma State,3431040
10,Jared Sullinger,Boston Celtics,7,C,24.0,6-9,260.0,Ohio State,2569260
11,Isaiah Thomas,Boston Celtics,4,PG,27.0,5-9,185.0,Washington,6912869
12,Evan Turner,Boston Celtics,11,SG,27.0,6-7,220.0,Ohio State,3425510
13,James Young,Boston Celtics,13,SG,20.0,6-6,215.0,Kentucky,1749840
14,Tyler Zeller,Boston Celtics,44,C,26.0,7-0,253.0,North Carolina,2616975
15,Bojan Bogdanovic,Brooklyn Nets,44,SG,27.0,6-8,216.0,No College,3425510
16,Markel Brown,Brooklyn Nets,22,SG,24.0,6-3,190.0,Oklahoma State,845059
17,Wayne Ellington,Brooklyn Nets,21,SG,28.0,6-4,200.0,North Carolina,1500000
18,Rondae Hollis-Jefferson,Brooklyn Nets,24,SG,21.0,6-7,220.0,Arizona,1335480
19,Jarrett Jack,Brooklyn Nets,2,PG,32.0,6-3,200.0,Georgia Tech,6300000
20,Sergey Karasev,Brooklyn Nets,10,SG,22.0,6-7,208.0,No College,1599840
21,Sean Kilpatrick,Brooklyn Nets,6,SG,26.0,6-4,219.0,Cincinnati,134215
22,Shane Larkin,Brooklyn Nets,0,PG,23.0,5-11,175.0,Miami (FL),1500000
23,Brook Lopez,Brooklyn Nets,11,C,28.0,7-0,275.0,Stanford,19689000
24,Chris McCullough,Brooklyn Nets,1,PF,21.0,6-11,200.0,Syracuse,1140240
25,Willie Reed,Brooklyn Nets,33,PF,26.0,6-10,220.0,Saint Louis,947276
26,Thomas Robinson,Brooklyn Nets,41,PF,25.0,6-10,237.0,Kansas,981348
27,Henry Sims,Brooklyn Nets,14,C,26.0,6-10,248.0,Georgetown,947276
28,Donald Sloan,Brooklyn Nets,15,PG,28.0,6-3,205.0,Texas A&M,947276
29,Thaddeus Young,Brooklyn Nets,30,PF,27.0,6-8,221.0,Georgia Tech,11235955
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8,SF,25.0,6-9,215.0,Wake Forest,8042895
429,Pat Connaughton,Portland Trail Blazers,5,SG,23.0,6-5,206.0,Notre Dame,625093
430,Allen Crabbe,Portland Trail Blazers,23,SG,24.0,6-6,210.0,California,947276
431,Ed Davis,Portland Trail Blazers,17,C,27.0,6-10,240.0,North Carolina,6980802
432,Maurice Harkless,Portland Trail Blazers,4,SF,23.0,6-9,215.0,St. John's,2894059
433,Gerald Henderson,Portland Trail Blazers,9,SG,28.0,6-5,215.0,Duke,6000000
434,Chris Kaman,Portland Trail Blazers,35,C,34.0,7-0,265.0,Central Michigan,5016000
435,Meyers Leonard,Portland Trail Blazers,11,PF,24.0,7-1,245.0,Illinois,3075880
436,Damian Lillard,Portland Trail Blazers,0,PG,25.0,6-3,195.0,Weber State,4236287
437,C.J. McCollum,Portland Trail Blazers,3,SG,24.0,6-4,200.0,Lehigh,2525160
438,Luis Montero,Portland Trail Blazers,44,SG,23.0,6-7,185.0,Westchester CC,525093
439,Mason Plumlee,Portland Trail Blazers,24,C,26.0,6-11,235.0,Duke,1415520
440,Brian Roberts,Portland Trail Blazers,2,PG,30.0,6-1,173.0,Dayton,2854940
441,Noah Vonleh,Portland Trail Blazers,21,PF,20.0,6-9,240.0,Indiana,2637720
442,Trevor Booker,Utah Jazz,33,PF,28.0,6-8,228.0,Clemson,4775000
443,Trey Burke,Utah Jazz,3,PG,23.0,6-1,191.0,Michigan,2658240
444,Alec Burks,Utah Jazz,10,SG,24.0,6-6,214.0,Colorado,9463484
445,Dante Exum,Utah Jazz,11,PG,20.0,6-6,190.0,No College,3777720
446,Derrick Favors,Utah Jazz,15,PF,24.0,6-10,265.0,Georgia Tech,12000000
447,Rudy Gobert,Utah Jazz,27,C,23.0,7-1,245.0,No College,1175880
448,Gordon Hayward,Utah Jazz,20,SF,26.0,6-8,226.0,Butler,15409570
449,Rodney Hood,Utah Jazz,5,SG,23.0,6-8,206.0,Duke,1348440
450,Joe Ingles,Utah Jazz,2,SF,28.0,6-8,226.0,No College,2050000
451,Chris Johnson,Utah Jazz,23,SF,26.0,6-6,206.0,Dayton,981348
452,Trey Lyles,Utah Jazz,41,PF,20.0,6-10,234.0,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8,PG,26.0,6-3,203.0,Butler,2433333
454,Raul Neto,Utah Jazz,25,PG,24.0,6-1,179.0,No College,900000
455,Tibor Pleiss,Utah Jazz,21,C,26.0,7-3,256.0,No College,2900000
456,Jeff Withey,Utah Jazz,24,C,26.0,7-0,231.0,Kansas,947276
457,NaN,NaN,0,NaN,NaN,NaN,NaN,No College,0

In [63]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000

In [65]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29.0,6-10,231.0,No College,5000000

.rank() method

In [74]:
nba = pd.read_csv("nba.csv").dropna(how = "all")
nba["Salary"] = nba["Salary"].fillna(0).astype("int")
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0

In [81]:
nba["Salary Rank"]  = nba["Salary"].rank(ascending = False).astype(int)
nba.head(3)
# tends to rank ascending paremeter

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337,97
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117,110
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452

In [85]:
nba.sort_values(by = "Salary", ascending = False).head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000,1
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500,2
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000,3